### ISSUE TITLE
No error messages on hanging consume flow

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/commons#131]
## Expected Behavior

GET FILE should succeed. If not, a popup should display, or some other feedback should appear. 

## Current Behavior

After successfully signing in MetaMask, and getting `Payment was OK` in console.log, the infinite progress bar circle keeps cycling, but no download initiates. No other feedback, after waiting >5 mins.

**Comment by kremalicious** [comment]
Technically correct because technically it is not failing. We just pass through what's coming from the components. And if it never aborts, we can't know when it's not successful. So nothing to show.

More message feedback is in https://github.com/oceanprotocol/commons/pull/110

So this issue is pretty much like https://github.com/oceanprotocol/commons/issues/86 or is it implying we should have a timeout and show an error then?
