### ISSUE TITLE
split up history into published/downloaded assets

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/commons#40]
Currently only lists published assets by owner. Should list more types, like assets downloaded by user.

**Comment by Kwinten-C** [comment]
**This issue is prerequisite for curation implementation**
Downloaded assets should display the vote a user gave to that asset (greyed out) and - in case of no vote - show a curate or vote button that take you to the asset view or the vote buttons themselves.

Add header for downloaded assets:
When all assets have been voted upon:
_Thanks for curating all your downloaded assets. Go to the Earn page to see when you can claim your rewards_
In case of assets that still require votes:
_Please rate the assets you have downloaded in order to be eligible for network rewards._

**Comment by Kwinten-C** [comment]
Also "Your Latest Published Data Sets" after metamask login, should not appear on front page IMO. It should be moved to history and replaced later with discovery as mentioned in https://github.com/oceanprotocol/commons/issues/118.
